overrides:
  pack:
    # Choose where the texturepack should be hosted (Requires server restaret)
    # Local = Makes a webserver on the Minecraft server (requires another open port)
    host-type: "local"
    # Default: 25566
    port: 25566
    # Default: Public ip
    host: 83.94.2.3
